# Generated by Django 2.0.6 on 2018-07-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180721_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagebanner',
            name='index',
            field=models.IntegerField(default=0, verbose_name='顺序'),
        ),
    ]
