# Generated by Django 2.0.6 on 2018-07-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20180718_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='need_know',
            field=models.CharField(default='', max_length=200, verbose_name='课程须知'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher_tell',
            field=models.CharField(default='', max_length=200, verbose_name='老师告知'),
        ),
    ]
